config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :articles, only: [:new,:show,:create,:destroy,:update] do
    resources :comments, only: [:create]
  end

  resources :users, only: [:show]
  root "articles#index"
  get 'articles/:id/edit' => 'articles#edit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :article, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    added_attrs = [ :name, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :destroy, :update, :edit]

  def index
    @article = Article.order("id DESC").page(params[:page]).per(5)
  end

  def new
    @article = Article.new
  end

  def show
    @comment = Comment.new
  end

  def create
    Article.create(create_params)
    redirect_to action: :index
  end

  def destroy
    @article.destroy if @article.user_id == current_user.id
    redirect_to action: :index
  end

  def update
    @article.update(create_params) if @article.user_id == current_user.id
    redirect_to action: :index
  end

  def edit
  end

  private
  def create_params
    params.require(:article).permit(:title,:article).merge(user_id:current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
  Comment.create(permit_params)
  redirect_to controller: :articles ,action: :show, id: params[:article_id]
end

private

def permit_params
  params.require(:comment).permit(:comment).merge(article_id: params[:article_id],user_id:current_user.id)
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @article = Article.where(user_id:params[:id]).order("id DESC").page(params[:page]).per(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m12 l8 offset-l2">
      <h2 class="center">投稿編集</h2>
      <%= form_for @article do |f| %>
        <div class="field">
          <%= f.label :タイトル入力 %><br />
          <%= f.text_field :title, placeholder: 'タイトルを入力' %>
        </div>
        <div class="field">
          <%= f.label :投稿記事 %><br />
          <%= f.text_area :article, placeholder: '記事を書いてください',class: "materialize-textarea", rows:"40" %>
        </div>
        <div class="actions waves-effect waves-light btn #fb8c00 orange darken-1 col s12 m6 offset-m3">
          <%= f.submit "編集する" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">
    <h2 class="center">投稿記事</h2>
    <% @article.each do |article|%>
      <%= render partial: "./shared/article", locals: {article: article} %>
    <% end %>
    <%= paginate(@article) %>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m12 l8 offset-l2">
      <h2 class="center">新規投稿</h2>
      <%= form_for @article do |f| %>
        <div class="field">
          <%= f.label :タイトル入力 %><br />
          <%= f.text_field :title, placeholder: 'タイトルを入力' %>
        </div>
        <div class="field">
          <%= f.label :投稿記事 %><br />
          <%= f.text_area :article, placeholder: '記事を書いてください',class: "materialize-textarea", rows:"40" %>
        </div>
        <div class="actions waves-effect waves-light btn #fb8c00 orange darken-1 col s12 m6 offset-m3">
          <%= f.submit "投稿する", class:"input-btn" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <h2 class="center">記事詳細</h2>
      <%= render partial: "./shared/article", locals: {article: @article} %>
  </div>

<% if @article.comments %>
  <h3>コメント一覧</h3>
    <%= render partial: "./shared/comment", locals: {article: @article} %>
<% end %>

<% if user_signed_in? %>
  <div class="row">
    <div class="col s12 m12 l12">
      <div class="form_contents">
        <%= form_for [@article, @comment] do |f| %>
          <div class="field">
            <%= f.label :コメントを書いてね %><br />
            <%= f.text_area :comment, placeholder: 'コメントを書いてね',class: "materialize-textarea validate", rows:"40"%>
          </div>
          <div class="actions waves-effect waves-light btn #fb8c00 orange darken-1 col s12 m6 offset-m3">
            <%= f.submit "投稿する", class:"input-btn" %>
          </div>
        <% end %>
    </div>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniAppKK</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>MiniApp_KK</title>
    <link rel="stylesheet" href="">
      <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>

  <body>
  <header class="header">
    <nav class="#ffa000 amber darken-2">
      <div class="nav-wrapper container">
          <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <%= link_to 'MiniApp_KK', root_path,class: "brand-logo" %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if user_signed_in? %>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
            </li>
            <li>
              <%= link_to '投稿', new_article_path %>
            </li>
            <li>
              <%= link_to 'マイページ', user_path(current_user.id) %>
            </li>
          <% else %>
            <li>
              <%= link_to '新規登録', new_user_registration_path %>
            </li>
            <li>
              <%= link_to 'ログイン', new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <ul id="slide-out" class="sidenav">
      <% if user_signed_in? %>
        <li><%= link_to destroy_user_session_path, method: :delete do%>
            <i class="material-icons">exit_to_app
</i> ログアウト
          <% end %>
        </li>
        <li>
          <%= link_to new_article_path do%>
            <i class="material-icons">send</i> 投稿
          <% end %>
        </li>
        <li>
          <%= link_to user_path(current_user.id) do%>
            <i class="material-icons">home</i> マイページ
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to new_user_registration_path do%>
            <i class="material-icons">assignment_ind</i> 新規登録
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
            <i class="material-icons">account_box</i> ログイン
          <% end %>
        </li>
      <% end %>
    </ul>
  </header>
    <main>
      <%= yield %>
    </main>
<footer class="page-footer #ffa000 amber darken-2">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      <p class="center">© 2018 Copyright Text</p>
    </div>
  </div>
</footer>
  <div class="scrollToTop btn-floating btn-large waves-effect">
    <i class="material-icons #ef6c00 orange darken-3">arrow_upward</i>
  </div>
  </body>
</html>

app/views/shared/_article.html.erb
<div class="row">
  <div class="card #f5f5f5 grey lighten-4">
    <div class="card-content black-text">
      <span class="card-title">
        <%= article.title %>
      </span>
      <p>
        <%= article.article %>
      </p>
    </div>
    <div class="card-action">
      <%= link_to '詳細画面', article_path(article.id) %>
      <% if user_signed_in? %>
        <% if article.user_id == current_user.id %>
          <%= link_to '編集', "/articles/#{article.id}/edit" %>
          <%= link_to '削除', article_path(article.id), method: :delete %>
        <% end %>
      <% end %>
    <div class="right indent">
      <i class="material-icons">account_circle
</i><span> <%= article.user.name%></span>
    </div>
    </div>
  </div>
</div>

app/views/shared/_comment.html.erb
<div class="row">
  <% article.comments.each do |comment| %>
    <div class="card #fff3e0 orange lighten-5">
      <div class="card-content black-text">
        <div class="comment_text_box article clearfix">
          <span class="card-title">
            <%= comment.user.name %>
          </span>
          <p><%= comment.comment %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
    <h2 class="center">マイページ</h2>
    <% @article.each do |article|%>
      <%= render partial: "./shared/article", locals: {article: article} %>
    <% end %>
    <%= paginate(@article) %>
</div>